---

- name: Create a workdir
  file:
    path: '{{ workdir }}'
    state: directory

- name: Add the apt sources list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Remove apache2 if it is installed
  apt:
    name: apache2
    state: absent
    autoremove: yes

- name: Install required packages
  apt:
    name: ['bash', 'python3', 'python3-pip', 'git', 'curl', 'nginx']
    state: latest 
    update_cache: yes 

- name: Clone the repo with the Flask app
  git: 
    repo: 'https://github.com/oleg1995petrov/flask-app-for-devops-course.git'
    dest: '{{ workdir }}'
    force: yes

- name: Install packages from the requirements.txt file
  pip:
    executable: pip3
    requirements: '{{ workdir }}/requirements.txt'
