---

- name: Create a directory for SSL certificates
  file:
    path: '{{ crt_dir }}'
    state: directory

- name: Generate an OpenSSL private key                                          
  community.crypto.openssl_privatekey:                                                            
    path: "{{ crt_dir }}/{{ host_name }}.pem"                                   
                                                                                 
- name: Generate an OpenSSL Certificate Signing Request 
  community.crypto.openssl_csr:                                                                  
    path: "{{ crt_dir }}/{{ host_name }}.csr"                                   
    privatekey_path: "{{ crt_dir }}/{{ host_name }}.pem"                                                 
    common_name: "{{ host_name }}"                                              
                                                                                
- name: Generate a self signed OpenSSL certificate                               
  community.crypto.x509_certificate:                                                           
    path: "{{ crt_dir }}/{{ host_name }}.crt"                                   
    privatekey_path: "/{{ crt_dir }}/{{ host_name }}.pem"                        
    csr_path: "{{ crt_dir }}/{{ host_name }}.csr"                               
    provider: selfsigned   

- name: Ensure the default nginx conf is removed
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create an nginx conf
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{ project_name }}'

- name: Ensure the nginx conf is enabled and nginx is reloaded
  file: 
    src: '/etc/nginx/sites-available/{{ project_name }}'
    dest: '/etc/nginx/sites-enabled/{{ project_name }}'
    state: link
  notify: Reload nginx
