---

- name: Create gunicorn daemon
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service

- name: Ensure gunicornd is started
  systemd:
    name: flask.service
    state: started
    enabled: yes
    daemon_reload: yes  